---
# 1. Check if cluster already exists
- name: Check if /etc/kubernetes/admin.conf exists
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubeadm_admin_conf

# 2. Create kubeadm config (only for first init)
- name: Create kubeadm config
  copy:
    dest: /root/kubeadm-config.yaml
    content: |
      apiVersion: kubeadm.k8s.io/v1beta4
      kind: ClusterConfiguration
      kubernetesVersion: stable-1.33
      controlPlaneEndpoint: "192.168.4.190:6443"
      networking:
        podSubnet: "172.16.0.0/16"
        serviceSubnet: "10.96.0.0/12"

      ---
      apiVersion: kubeadm.k8s.io/v1beta4
      kind: InitConfiguration
      nodeRegistration:
        name: "master1"
        criSocket: "unix:///var/run/crio/crio.sock"
  when: not kubeadm_admin_conf.stat.exists

# 3. kubeadm init
- name: kubeadm init on master1
  command: kubeadm init --config=/root/kubeadm-config.yaml --upload-certs
  register: init_out
  args:
    creates: /etc/kubernetes/admin.conf
  when: not kubeadm_admin_conf.stat.exists

# 4. Upload certs
- name: Upload certificates and get certificate key
  command: kubeadm init phase upload-certs --upload-certs
  register: certs
  become: yes
  run_once: true

# 5. Generate join commands
- name: Generate base join command
  command: kubeadm token create --print-join-command
  register: join_base
  become: yes
  run_once: true

- name: Set join commands facts
  set_fact:
    join_cmd_worker: "{{ join_base.stdout }}"
    join_cmd_master: >-
      {{ join_base.stdout }}
      --control-plane
      --certificate-key {{ certs.stdout_lines[-1] }}
  run_once: true
  delegate_to: master1

# 6. Debug join commands
- debug:
    msg:
      - "MASTER JOIN: {{ join_cmd_master }}"
      - "WORKER JOIN: {{ join_cmd_worker }}"
  run_once: true

# 7. Kubeconfig for wolf
- name: Create ~/.kube directory
  file:
    path: /home/wolf/.kube
    state: directory
    owner: wolf
    group: wolf
    mode: '0755'
  become: yes

- name: Copy kubeconfig to wolf user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/wolf/.kube/config
    remote_src: yes
    owner: wolf
    group: wolf
    mode: '0600'
  become: yes
  when: kubeadm_admin_conf.stat.exists
