- import_playbook: 2_keepalived.yml
- import_playbook: 3_ca_import_latloto.yml
- import_playbook: 4_k8s_ha.yml
- import_playbook: 4.1_join_cluster.yml
- import_playbook: 5_install_helm.yml
- import_playbook: 6_python.yml
- import_playbook: 6.1_metallb.yml
- import_playbook: 7_traefik_site.yml
# - import_playbook: 8_data_app_site.yml
# - import_playbook: 9_hoami_app.yml
- import_playbook: 10_install_awx_full.yml



# ansible-playbook -i hosts.ini 0_setup.yml
# ansible-playbook -i hosts_wolf.ini 1_master_playbook.yml