---
# 1. Pārbaudīt, vai mezgls jau ir control-plane
- name: Pārbaudīt, vai master jau pievienots
  stat:
    path: /etc/kubernetes/pki/ca.key
  register: master_joined

# 2. Ja nav – pievienot klāsterim kā master (control-plane)
- name: Pievienot pārējos master mezglus
  become: yes
  shell: "{{ hostvars['master1'].join_cmd_master }}"
  args:
    creates: /etc/kubernetes/pki/ca.key
  when: not master_joined.stat.exists

# 3. Izveidot ~/.kube direktoriju wolf lietotājam
- name: Izveidot ~/.kube direktoriju
  become: yes
  file:
    path: /home/wolf/.kube
    state: directory
    owner: wolf
    group: wolf
    mode: '0755'
  when: master_joined.stat.exists

# 4. Kopēt kubeconfig uz wolf profilu
- name: Kopēt kubeconfig uz wolf profilu
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/wolf/.kube/config
    remote_src: yes
    owner: wolf
    group: wolf
    mode: '0600'
  when: master_joined.stat.exists
