---
- name: Deploy Weave Net CNI
  command: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  run_once: true