apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
  annotations:
    # 1. Traefik anotācija, lai veiktu HTTP uz HTTPS novirzīšanu
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-to-https@kubernetescrd
spec:
  # 2. TLS sertifikāta definīcija
  tls:
  - hosts:
    - hello.iloto.lldev
    secretName: iloto-wildcard-tls # Nosaukums jūsu secret, kas atrodas "traefik" namespace!

  # 3. Ingress noteikumi
  rules:
  - host: hello.iloto.lldev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-app # Tas būs bitnami/nginx servisa nosaukums (pēc noklusējuma tāds)
            port:
              number: 80 # Nginx ports