# whoami-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deployment-app
  namespace: default
  labels:
    app: whoami-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami-app
  template:
    metadata:
      labels:
        app: whoami-app
    spec:
      containers:
      - name: whoami-app
        image: traefik/whoami:latest
        ports:
        - containerPort: 80

# KUBECONFIG=/etc/kubernetes/admin.conf
# sudo kubectl apply -f whoami-deployment.yaml --kubeconfig $KUBECONFIG
# sudo kubectl apply -f whoami-service.yaml --kubeconfig $KUBECONFIG
# sudo kubectl apply -f whoami-ingressroute.yaml --kubeconfig $KUBECONFIG