apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    # Piesaistīt Middleware novirzīšanai
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-to-https@kubernetescrd 
spec:
  tls:
  - hosts:
    - hello.iloto.lldev
    secretName: iloto-wildcard-tls
  rules:
  - host: hello.iloto.lldev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-app
            port:
              number: 80